language: csharp
solution: ECSLight.sln
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore ECSLight.sln
script:
  - xbuild /p:Configuration=Debug ECSLight.sln
  - nunit-console Tests/bin/Debug/Tests.dll
