language: csharp
solution: ECSLight.sln
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore ECSLight.sln
script:
  - xbuild /p:Configuration=Debug ECSLight.sln
  - nunit-console Tests/bin/Debug/Tests.dll

# gitter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9c8bd47255f8eb30665
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
